datarobot_provider/example_dags/datarobot_pipeline_dag.py
tests/unit/dags/test_datarobot_pipeline_dag.py

Address minor comments from Astronomer.

---

README.md
datarobot_provider/__init__.py
datarobot_provider/hooks/datarobot.py
datarobot_provider/operators/datarobot.py
requirements.txt
setup.py
tests/unit/operators/test_datarobot.py

Enable project creation with a local training data file. Bump version to v0.0.3

---

README.md
datarobot_provider/__init__.py
datarobot_provider/example_dags/datarobot_dataset_upload_dag.py
datarobot_provider/example_dags/datarobot_score_dag.py
datarobot_provider/operators/ai_catalog.py
setup.py
tests/unit/operators/test_ai_catalog.py

Added new Airflow Operator for Uploading local file to DataRobot AI Catalog
Bump version to 0.0.5
Uploading local file to DataRobot AI Catalog is important missing part in out Airflow Provider

[AGENT-4318] Implement UploadDatasetOperator

---

CODEOWNERS
jenkins/build_and_publish.groovy
jenkins/style_check.groovy
pipelineController.yaml

- Update standalone job definition
- Add notes about more Jenkins updates
The syntax was incorrect so update job def

Fix standalone job def

---

datarobot_provider/example_dags/datarobot_jdbc_dataset_dag.py
datarobot_provider/hooks/connections.py

Fixed error handling for case where user added wrong JDBC Driver name
User should get proper error message in case of wrong JDBC Driver name

[AGENT-4434] Fix for error handling for case of using wrong JDBC Driver name

---

datarobot_provider/__init__.py
datarobot_provider/hooks/credentials.py
tests/unit/conftest.py
tests/unit/hooks/credentials/test_azure_credentials.py
tests/unit/operators/test_credentials.py

Added support for Azure Storage Credentials Management from Airflow
Users should be able to configure and use DataRobot Azure Storage Credentials from Airflow UI

[AGENT-4241] Implement Azure Credentials management

---

README.md
datarobot_provider/__init__.py
datarobot_provider/example_dags/datarobot_aws_s3_batch_scoring_dag.py
datarobot_provider/example_dags/datarobot_azure_storage_batch_scoring_dag.py
datarobot_provider/example_dags/datarobot_gcp_storage_batch_scoring_dag.py
datarobot_provider/example_dags/datarobot_jdbc_dataset_dag.py
datarobot_provider/operators/ai_catalog.py
datarobot_provider/operators/connections.py
datarobot_provider/operators/credentials.py
requirements.txt
setup.py
tests/unit/operators/test_ai_catalog.py
tests/unit/operators/test_credentials.py

Added description for new DataRobot operators and connections, renamed Operators to make naming more consistent,
fixed minor issues.
We should provide clear description on how to use new operators

[AGENT-4246] Update documentation for new operators

---

datarobot_provider/example_dags/datarobot_bigquery_batch_scoring_dag.py
datarobot_provider/example_dags/datarobot_jdbc_batch_scoring_dag.py
datarobot_provider/hooks/connections.py

Added Airflow DAG examples for Batch Scoring with BigQuery and JDBC
Example of using Airflow to automate scoring with BigQuery is one of the most frequent client asked questions. Also example of Batch Scoring  with JDBC will cover support for variety of SQL databases

[AGENT-4509] Create Airflow DAG examples for Batch Scoring

---

datarobot_provider/example_dags/datarobot_upload_actuals_ai_catalog_dag.py
datarobot_provider/example_dags/datarobot_upload_actuals_catalog_dag.py
datarobot_provider/hooks/datarobot.py
datarobot_provider/operators/mlops.py
datarobot_provider/sensors/client.py
tests/unit/operators/test_mlops.py

Added SubmitActualsFromCatalogOperator and BaseAsyncResolutionSensor to support async uploading actuals from AI Catalog
Users should be able to submit actuals from the AI Catalog

[AGENT-4237] Implement Airflow Operator for Submitting actuals

---

datarobot_provider/example_dags/datarobot_dataset_new_version_dag.py
datarobot_provider/example_dags/deployment_stat_and_accuracy_dag.py
datarobot_provider/hooks/credentials.py

-Fixed example DAG to work with regression and classification
-Changed to password field type for GCP json secret key
-Adding fixes after QA test

[QA-9233] DAG examples failures

---

datarobot_provider/example_dags/model_compute_insights_dag.py
datarobot_provider/operators/model_insights.py
datarobot_provider/sensors/model_insights.py
tests/unit/operators/test_model_insights_job.py
tests/unit/sensors/test_model_insights_job.py

Added ComputeFeatureImpactOperator and ComputeFeatureImpactSensor
Added unit-tests and example Airflow DAG
Users should be able to Kickoff FeatureImpact job for a model

[AGENT-4234] Implement Airflow Operator to Kickoff feature impact

---

datarobot_provider/example_dags/model_compute_insights_dag.py
datarobot_provider/operators/model_insights.py
datarobot_provider/sensors/model_insights.py
tests/unit/operators/test_model_insights_job.py
tests/unit/sensors/test_model_insights_job.py

Added ComputeFeatureEffectsOperator
Added DataRobotJobSensor - as unified sensor for model insights, removed ComputeFeatureImpactSensor
Added unit-tests
Extended sample Airflow DAG
Users should be able to kickoff Feature Effects Computations

[AGENT-4684] Implement Airflow Operator to kickoff Feature Effects

---

datarobot_provider/example_dags/model_compute_prediction_explanations_dag.py
datarobot_provider/example_dags/model_compute_predictions_dag.py
datarobot_provider/operators/prediction_explanations.py
tests/unit/operators/test_model_predictions_explanations.py

Added PredictionExplanationsInitializationOperator and ComputePredictionExplanationsOperator
users should be able to compute prediction explanations on external dataset

[AGENT-4686] Implement Airflow Operator to Kickoff Prediction Explanations

---

README.md

Basic copyedit and reformatting for the README.
Align the README with the documentation formatting used on the doc site.

[DOC-5252] Airflow README updates

---

datarobot_provider/example_dags/model_compute_prediction_explanations_dag.py
datarobot_provider/example_dags/model_compute_predictions_dag.py
datarobot_provider/example_dags/model_train_dag.py
datarobot_provider/operators/model_training.py
datarobot_provider/sensors/model_insights.py
datarobot_provider/sensors/model_training.py
tests/unit/operators/test_model_predictions_explanations.py
tests/unit/operators/test_model_training.py
tests/unit/sensors/test_model_training.py

Added TrainModelOperator and ModelTrainingJobSensor for model training using specific blueprint
users should be able to train a model using specific blueprint

[AGENT-4682] Implement Airflow Operators for Training a specific blueprint 

---

datarobot_provider/example_dags/datarobot_feature_discovery_pipeline_dag.py
datarobot_provider/operators/autopilot.py
datarobot_provider/operators/feature_discovery.py
tests/unit/operators/test_autopilot.py
tests/unit/operators/test_feature_discovery.py

Added Airflow Operators to setup a Feature Discovery project:
- RelationshipsConfigurationOperator
- DatasetDefinitionOperator
- DatasetRelationshipOperator
Added sample DAG to setup a Feature Discovery project.
Users should be able to setup Feature Discovery projects using Airflow Operators.

[AGENT-4701] Implement Airflow Operators to setup a Feature Discovery project

---

datarobot_provider/example_dags/datarobot_create_execution_environment_dag.py
datarobot_provider/operators/execution_environment.py
tests/unit/operators/test_execution_environment.py

Implemented CreateExecutionEnvironmentOperator to create Custom Execution Environment
Users should be able to create Custom Execution Environment using Airflow operators

[AGENT-4712] Implement Airflow Operator for Execution Environment Creation

---

datarobot_provider/example_dags/datarobot_create_execution_environment_dag.py
datarobot_provider/operators/execution_environment.py
tests/unit/operators/test_execution_environment.py

implemented CreateExecutionEnvironmentVersionOperator to create new version of Execution Environment
added unit-tests
extended sample DAG
Users should be able to create Execution Environment Version using Airflow operators

[AGENT-4710] Implement Airflow Operator to create an Execution Environment Version

---

datarobot_provider/example_dags/datarobot_datetime_partitioning_pipeline_dag.py
datarobot_provider/operators/autopilot.py

Added Airflow sample DAG for datetime partitioning project (OTV)
Most of work was done in scope of [AGENT-4669] Implement/extend Airflow Operators to set up a Time Series project
Users should be able to setup datetime partitioning project using Airflow Operators
[AGENT-4669]: https://datarobot.atlassian.net/browse/AGENT-4669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AGENT-4670] Implement extend Airflow Operators to set-up a datetime partitioning project

---

datarobot_provider/example_dags/deployment_activate_deactivate_dag.py
datarobot_provider/operators/deployment.py
tests/unit/operators/test_deployment.py

Implemented Airflow Operator to get Deployment Status
Implemented Airflow Operator for Deactivate/Activate Deployment
Added sample DAG
Users should be able to Deactivate/Activate Deployment using Airflow operators

[AGENT-4711] Implement Airflow Operator for Deactivate/Activate Deployment

---

datarobot_provider/example_dags/datarobot_custom_model_pipeline_dag.py
datarobot_provider/operators/custom_models.py
tests/unit/operators/test_custom_models.py

Added operator to create Custom model Test: CustomModelTestOperator
Added operator to get Custom model Test status GetCustomModelTestOverallStatusOperator
added sample DAG for custom model pipeline
users should be able to create and execute Custom Model Tests using Airflow operators

[AGENT-4705] Implement Airflow Operator for adding training data to Custom model Test

---

datarobot_provider/example_dags/datarobot_custom_model_pipeline_dag.py
datarobot_provider/operators/custom_models.py
tests/unit/operators/test_custom_models.py

Added DeployCustomModelOperator to support deployment from a Custom Models
Added sample DAG
Added unit-tests
Users should be able to create Custom Model Deployments using Airflow Operators

[AGENT-4704] Implement Airflow Operator for Custom Model Deployment

---

datarobot_provider/example_dags/datarobot_replace_custom_model_pipeline_dag.py
datarobot_provider/operators/deployment.py

fixed ReplaceModelOperator to support model replacement in case of "warning" status
added custom model replacement pipeline for existing deployment
users should be able to replace model in existing deployment

[AGENT-4929] fixed ReplaceModelOperator added new sample DAG

---

datarobot_provider/example_dags/datarobot_batch_scoring_templated_dag.py
datarobot_provider/operators/datarobot.py

[AGENT-5077] Airflow provider Scoring operator not supporting execution_date template

---

datarobot_provider/__init__.py
datarobot_provider/example_dags/datarobot_batch_scoring_templated_dag.py
datarobot_provider/operators/datarobot.py
requirements.txt
setup.py

Python client updated to 3.3
Increased provider version to 0.0.8

[AGENT-5159] Bump python client version in DataRobot Provider for Airflow

---

datarobot_provider/example_dags/datarobot_batch_scoring_templated_dag.py

[AGENT-5168] Example DAG for templated Batch Scoring provided with invalid sample config

---

.harness/default_unit_tests_input_set.yaml
.harness/unit_tests.yaml

Added unit-tests to the cicd pipeline

[AGENT-5162] Adding cicd unit-tests pipeline

---

datarobot_provider/__init__.py
setup.py

[PRED-11010] Bump version to 0.0.10

---

datarobot_provider/example_dags/hospital_readmissions_example.py
datarobot_provider/operators/ai_catalog.py
datarobot_provider/operators/datarobot.py
tests/unit/operators/test_ai_catalog.py
tests/unit/operators/test_datarobot.py

* Use csv upload in the example DAG
* Reuse a use case by name
* Add more operations into the example recipe
Provide as smooth quick start experience as possible:
* Use public data with no additional configurations needed
* Create and reuse a use case

[DM-16908] Better dag

---

datarobot_provider/autogen/generate_operator.py
datarobot_provider/hooks/credentials.py
datarobot_provider/operators/ai_catalog.py
datarobot_provider/operators/base_datarobot_operator.py
datarobot_provider/operators/datarobot.py
pyproject.toml

Added some new mypy rules and fixed related errors
Also added more rules that we should try and enable, fix errors and then have them moving forward
I believe the more we can enforce mypy rules the better guardrails we'll have in place and it will also lead to more informative code as we annotate things better

[CFX-1590] Mypy rule updates and prompted related updates

---

datarobot_provider/example_dags/hospital_readmissions_xgboost_example.py
datarobot_provider/operators/datarobot.py
datarobot_provider/operators/model_insights.py
tests/unit/operators/test_model_insights_job.py

Updates to the DAG and supported functions to add waiting for the model to finish training and generating default insights. **This basically cleans up everything to run all the way through.**
DAG is running through to the end in the latest build run locally against production:

[MLDEV-1231] Add insights and model sensor to example P0 DAG #1

---

datarobot_provider/example_dags/hospital_readmissions_deployment_prediction_generation.py

Fix some casting and remove a parameter to allow this DAG to work in all environments. I also added a link to how to get the predictions server ID and an extra sensor to verify the predictions completed.

[MODEL-18026] Fix P0 Dag 2 for release

---

datarobot_provider/example_dags/model_training_xgboost.py
datarobot_provider/operators/ai_catalog.py
tests/unit/operators/test_ai_catalog.py

Modify an xgboost example DAG to use a snowflake db data.
Users need a db data preparation example.

[DM-17363] DB data prep

---

CHANGES.md
datarobot_provider/__init__.py
datarobot_provider/_version.py

Bump version to `0.3.0` for the weekly release.

[MODEL-18291] Bump for release 0.3.0

---

.github/pull_request_template.md
CHANGES.md

This updates the `pull_request_template` to include a PR checklist to helps reviewers and authors with changelogs and docs.
- Update `.github/pull_request_template.md`

[MODEL-18297] Update the default PR template

---

README.md

Updating README steps related to release pipelines
Updated README steps related to release pipelines

[-] Update readme related to release pipelines

---

README.md
datarobot_provider/operators/data_prep.py
setup.py
tests/unit/operators/test_data_prep.py

This PR was initially intended as just an update to the readme, but it also provides a fix for a change introduced in the datarobot 3.7 public SDK.
- Update readme
- Fix tests/calls
- Bump compatibility for datarobot 3.7

[MODEL-18594] Update README.md

---

datarobot_provider/operators/mlops.py
tests/unit/operators/test_mlops.py

Implement operator to upload actuals

[MMM-18326]: implement operator to upload actuals
