README.md, datarobot_provider/example_dags/datarobot_pipeline_dag.py, datarobot_provider/operators/datarobot.py, tests/unit/dags/test_datarobot_pipeline_dag.py, tests/unit/operators/test_datarobot.py
Adding two operators `GetFeatureDriftOperator` and `GetTargetDriftOperator` so that users can check for drift after running batch scoring in their pipelines.
Most changes were implemented by @zingbretsen in https://github.com/datarobot/airflow-provider-datarobot/pull/5 and moved to this PR.
It can be useful to check for drift after running predictions. This allows users to do it from Airflow if they want to automate the process, and then trigger other events if drift was detected.
=> Add operators to get target drift and feature drift.

datarobot_provider/example_dags/datarobot_score_dag.py, datarobot_provider/operators/datarobot.py, tests/unit/operators/test_datarobot.py
Extended CreateProjectOperator to support creating projects from dataset_id
In most of the cases customers uploading their datasets to AICatalog to reuse it many times.
So its must-have ability to create DR projects from datasets previously uploaded to AICatalog using dataset_id
=> [AGENT-4334] Extended CreateProjectOperator to support creating project from dataset_id

README.md, datarobot_provider/example_dags/datarobot_create_project_from_ai_catalog_dag.py, datarobot_provider/example_dags/datarobot_dataset_upload_create_project_dag.py, tests/unit/dags/test_create_project_from_ai_catalog_dag.py
Added Example of Airflow DAG using recently added new operators (UploadDatasetOperator and extended CreateProject Operator). This DAG uploading local file to DataRobot AICatalog as a static dataset, then using this stored dataset as a training data to create a DataRobot Project.
When we adding new Airflow Operators or extending existing, it's very crucial to provide number of usage examples to make learning curve as easy as possible
=> [AGENT-4337] Add Airflow DAG example Uploading Dataset to AICatalog and Creating Project

datarobot_provider/hooks/datarobot.py
Added Airflow-provider version specific header suffix to DataRobot API invocations 
To collect Airflow Provider usage statistics and troubleshooting proposes
=> [AGENT-4348] Add Airflow provider specific header suffix to DataRobot API invocations

jenkins/build_and_publish.groovy
fix for pypi upload url
Default pypi upload url should be "https://upload.pypi.org/legacy/" instead of "https://pypi.org/legacy/"
=> fix for pypi upload url

datarobot_provider/example_dags/datarobot_create_project_from_dataset_version_dag.py, datarobot_provider/operators/ai_catalog.py, datarobot_provider/operators/datarobot.py, tests/unit/dags/test_create_project_from_dataset_version_dag.py, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_datarobot.py
Added Airflow operator "UpdateDatasetFromFileOperator" that allows to create a new version of existing dataset by uploading a local file.
Also CreateProjectOperator extended to support specific dataset_version_id
We need to allow users to update their existing datasets in AI Catalog with new versions of data
=> [AGENT-4349] Implement-UpdateDatasetFromFileOperator

datarobot_provider/__init__.py, datarobot_provider/hooks/credentials.py, datarobot_provider/operators/credentials.py, tests/unit/conftest.py, tests/unit/hooks/test_basic_credentials.py, tests/unit/hooks/test_gcp_credentials.py, tests/unit/operators/test_credentials.py
Added support for GCP Credentials, extended GetCredentialIdOperator to support fetching existing Credentials or replicating Credentials based on stored Airflow connection 
added unit-tests
Users should be able to create GCP credentials form Airflow, and use it for scoring and project creation
=> [AGENT-4242] add gcp credentials management from airflow

datarobot_provider/__init__.py, datarobot_provider/hooks/credentials.py, tests/unit/conftest.py, tests/unit/hooks/credentials/__init__.py, tests/unit/hooks/credentials/test_aws_credentials.py, tests/unit/hooks/credentials/test_basic_credentials.py, tests/unit/hooks/credentials/test_gcp_credentials.py, tests/unit/hooks/test_connections.py, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_credentials.py
Added support for storing and using AWS credentials on Airflow side
Users should be able to create DataRobot credentials for AWS using  Airflow UI
=> [AGENT-4240] Add AWS credentials support

datarobot_provider/__init__.py, datarobot_provider/hooks/credentials.py, tests/unit/conftest.py, tests/unit/hooks/credentials/test_oauth_credentials.py
Added OAuth credentials type hook to configure and store it as an Airflow connection
Users should be able to store OAuth credentials using  Airflow secure storage
=> [AGENT-4239] added oauth credentials support

datarobot_provider/__init__.py, datarobot_provider/example_dags/datarobot_get_datastore_dag.py, datarobot_provider/hooks/credentials.py, datarobot_provider/operators/connections.py, tests/unit/operators/test_connections.py
Added CreateDataStoreOperator that returned datastore_id by connection name. It creates new datastore using preconfigured jdbc connection in case if connection not exist
users should be able to fetch datastore_id for existing connections because it required for different operators
=> [AGENT-4245] Implement CreateDataStoreOperator

datarobot_provider/__init__.py, datarobot_provider/example_dags/datarobot_jdbc_dynamic_dataset_dag.py, datarobot_provider/hooks/connections.py, datarobot_provider/hooks/credentials.py, datarobot_provider/operators/ai_catalog.py, datarobot_provider/operators/connections.py, datarobot_provider/operators/datarobot.py, tests/unit/conftest.py, tests/unit/hooks/test_connections.py, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_connections.py, tests/unit/operators/test_datarobot.py
- fixed issue with connection type delimiter switched from ":" to "."
- now JDBCDataSourceHook extending BasicCredentialsHook to support basic credentials for Project Creation and Batch Scoring with JDBC
- added example of project creation from dynamic jdbc dataset: datarobot_jdbc_dynamic_dataset_dag
- fixed unit-tests
Users should be able to use dynamic datasets for project creation.
Fixed bug related to connection type delimiter
=> [AGENT-4494]-connections-refactoring-and-bug-fixes

datarobot_provider/example_dags/deployment_service_stats_dag.py, datarobot_provider/operators/monitoring.py, tests/unit/operators/test_monitoring.py
Implemented GetServiceStatsOperator to read Deployment metrics and serialize it to pass to the next operator with user logic. Added example DAG with GetServiceStatsOperator and custom Python operator template
Users should be able to read service metrics from Deployment to use it with their custom logic
=> [AGENT-4488] Implement Airflow Operator for reading Deployment metrics

datarobot_provider/example_dags/datarobot_aws_s3_batch_scoring_dag.py, datarobot_provider/example_dags/datarobot_azure_storage_batch_scoring_dag.py, datarobot_provider/example_dags/datarobot_bigquery_batch_scoring_dag.py, datarobot_provider/example_dags/datarobot_create_project_from_ai_catalog_dag.py, datarobot_provider/example_dags/datarobot_create_project_from_dataset_version_dag.py, datarobot_provider/example_dags/datarobot_dataset_new_version_dag.py, datarobot_provider/example_dags/datarobot_dataset_upload_dag.py, datarobot_provider/example_dags/datarobot_gcp_storage_batch_scoring_dag.py, datarobot_provider/example_dags/datarobot_get_datastore_dag.py, datarobot_provider/example_dags/datarobot_jdbc_batch_scoring_dag.py, datarobot_provider/example_dags/datarobot_jdbc_dataset_dag.py, datarobot_provider/example_dags/datarobot_jdbc_dynamic_dataset_dag.py, datarobot_provider/example_dags/datarobot_pipeline_dag.py, datarobot_provider/example_dags/datarobot_score_dag.py, datarobot_provider/example_dags/deployment_service_stats_dag.py, datarobot_provider/example_dags/deployment_stat_and_accuracy_dag.py, datarobot_provider/operators/ai_catalog.py, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_monitoring.py
Added Airflow Operators: CreateDatasetVersionOperator and CreateDatasetFromDataStoreOperator to support creating new versions of existing datasets
changed "schedule_interval" to "schedule" for all DAGs because "schedule_interval" was deprecated
Users should be able to create new versions of existing datasets in AI Catalog. Also it required for submit actuals DAG because "dynamic" dataset is not supported for submit actuals method
=> [AGENT-4486] Implement Airflow Operators to create new dataset versions from datasource

datarobot_provider/example_dags/datarobot_dataset_new_version_dag.py, datarobot_provider/example_dags/deployment_update_monitoring_settings_dag.py, datarobot_provider/operators/monitoring.py, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_monitoring.py
Added GetMonitoringSettingsOperator and UpdateMonitoringSettingsOperator Airflow operators and simple DAG example
Users should be able to get and configure monitoring setting using Airflow Operators
=> [AGENT-4485] Create Operator to configure Monitoring Settings for a deployment

requirements.txt, tests/unit/operators/test_datarobot.py
temporary switched to “datarobot-early-access>=3.2.0.2023.6.19” to pass tests
=> [AGENT-4596] changed to datarobot-early-access

datarobot_provider/example_dags/deployment_update_segment_analysis_settings_dag.py, datarobot_provider/operators/bias_and_fairness.py, datarobot_provider/operators/segment_analysis.py, tests/unit/operators/test_bias_and_fairness.py, tests/unit/operators/test_segment_analysis.py
added the next new Airflow Operators:
- GetSegmentAnalysisSettingsOperator
- UpdateSegmentAnalysisSettingsOperator
- GetBiasAndFairnessSettingsOperator
- UpdateBiasAndFairnessSettingsOperator
also added sample DAG
users should be able to configure Segment Analysis and Bias&Fairness Settings using Airflow operators
=> [AGENT-4491] Implement Airflow Operator to turn on segmentation, bias and fairness thresholds

datarobot_provider/example_dags/download_scoring_code_from_deployment_dag.py, datarobot_provider/operators/scoring_code.py, requirements.txt, tests/unit/operators/test_scoring_code.py
Added Airflow DAG predictions examples with Scoring Code
Added Operators for scoring code downloading from deployment and from model
Users should be able to use Airflow with scoring code to run predictions
=> [AGENT-4613] Add Airflow DAG predictions examples with Scoring Code

setup.py
Upgrade datarobot client to 3.2.0b1
This version is needed to support all new operators
=> Upgrade datarobot client to 3.2.0b1 in setup.py

README.md, datarobot_provider/example_dags/advanced_datarobot_pipeline_jdbc_dag.py
Added Airflow DAG example to advanced end-to-end pipeline which contains following steps:
- Ingestion dataset to AICatalog from JDBC datasource
- Create Project
- Train models using Autopilot mode
- Deploy Recommended model
- Change Deployment settings: enable monitoring settings, segment analysis, bias and fairness
- Run Batch Scoring
- Upload Actuals
- Collect Deployment metrics: service statistics, features drift, target drift, accuracy and process it with custom python operator
Users should be able to use provided examples to reuse it to speedup custom DAGs creation process
=> [AGENT-4687] Add advanced end-to-end pipeline DAG example

datarobot_provider/example_dags/model_compute_predictions_dag.py, datarobot_provider/operators/model_predictions.py, tests/unit/operators/test_model_predictions.py
Implemented AddExternalDatasetOperator to support model predictions and prediction explanations for external dataset
Users should be able to add external datasets to the model
=> [AGENT-4765] Implement Airflow Operator to add external dataset to the Project

datarobot_provider/example_dags/model_compute_predictions_dag.py, datarobot_provider/operators/model_predictions.py, tests/unit/operators/test_model_predictions.py
added RequestModelPredictionsOperator to request predictions from model
extended sample DAG: model_compute_predictions_dag.py
added unit-tests
Users should be able to run model predictions on external dataset for testing for model testing proposes
=> [AGENT-4766] Implement Airflow Operator to request model predictions on external dataset

README.md, requirements.txt, setup.py
upgraded DataRobot python client to 3.2.0
upgraded DataRobot python client to 3.2.0
=> [AGENT-4806] upgraded DataRobot python client to 3.2.0

datarobot_provider/example_dags/model_compute_shap_dag.py, datarobot_provider/operators/model_insights.py, tests/unit/operators/test_model_insights_job.py
Added ComputeShapOperator that creates SHAP impact job in DataRobot
Users should be able to Kickoff SHAP impact compute using airflow operators
=> [AGENT-4685] Implement Airflow Operator to Kickoff SHAP

datarobot_provider/example_dags/datarobot_autopilot_options_pipeline_dag.py, datarobot_provider/example_dags/datarobot_custom_partitioning_pipeline_dag.py, datarobot_provider/example_dags/datarobot_timeseries_pipeline_dag.py, datarobot_provider/operators/autopilot.py, datarobot_provider/operators/project.py, tests/unit/operators/test_autopilot.py
Added StartAutopilotOperator to support datetime_partitioning_settings, partitioning_settings and advanced_options
Added sample DAGs and unit-tests
Users should be able to create time-series projects and configure partitioning_settings and advanced_options
=> [AGENT-4669] Implement Airflow Operators to set up a Time Series project

datarobot_provider/example_dags/datarobot_external_model_pipeline_dag.py, datarobot_provider/operators/model_package.py, tests/unit/operators/test_model_package.py
Added CreateExternalModelPackageOperator to support  External Model package creation
Added sample DAG (will be extended)
Added unit-tests
Users should be able to create External Model package using Airflow Operators
=> [AGENT-4707] Implement Airflow Operator for External Creating Model package

datarobot_provider/example_dags/datarobot_aws_s3_batch_scoring_dag.py, datarobot_provider/hooks/credentials.py, datarobot_provider/operators/credentials.py, jenkins/unit_test.groovy
Extended Airflow DataRobot hooks to support updating credentials after creation,
currently its updating credentials each time when GetOrCreateCredentials method invoked
Users should be able to update DataRobot Credentials/ Connections from Airflow Connection Tab
=> [AGENT-4700] Add support for DataRobot Credentials update from Airflow Connection Tab

datarobot_provider/operators/custom_models.py, tests/unit/operators/test_custom_models.py
Extended CreateCustomModelVersionOperator to create Custom Model Version from previous.
Added unit-tests
Users should be able to create new Custom Model version from previous version
=> [AGENT-4703] Extended Airflow Operator to create Custom Inference Version from previous

datarobot_provider/example_dags/datarobot_external_model_pipeline_dag.py, datarobot_provider/operators/model_package.py, tests/unit/operators/test_external_deployment.py
Added DeployModelPackageOperator for creating deployment from model package
extended sample DAG
added unit-tests
users should be able to create external model deployment using Airflow operators
=> [AGENT-4708] Implement Airflow Operator for creating deployment from Model Package

datarobot_provider/example_dags/datarobot_custom_model_pipeline_dag.py, datarobot_provider/operators/ai_catalog.py
Added option to configure dataset file path from operator arguments
For some use-cases its mandatory to upload files from different source file path
=> [AGENT-4924] Extend dataset upload operator to support configurable param name

datarobot_provider/example_dags/datarobot_custom_model_pipeline_dag.py, datarobot_provider/hooks/datarobot.py
Changed to trace_context because of user_agent_suffix deprecation
Changed to trace_context because of user_agent_suffix deprecation
=> [AGENT-4928] Fix warning related to user_agent_suffix deprecation

.harness/default_input_set.yaml, .harness/lint_check.yaml
- Added harness pipeline with lint check and configured trigger for each commit in scope of migrating cicd pipelines to harness.io
=> [AGENT-5162] Migrate cicd pipelines for repository airflow-provider-datarobot to harness added lint check

.harness/build_and_publish_pipy.yaml
Added build-and-publish cicd pipeline to harness.io
=> [AGENT-5162] Adding build-and-publish cicd pipeline to harness

CODEOWNERS, datarobot_provider/operators/credentials.py, tests/unit/operators/test_credentials.py
=> [PRED-11010] Fix GetOrCreateCredentialOperator occurring when JDBCDataSourceHook is used.

README.md
This is a small update to the readme to include some new and relevant information for constructing a simple testing/development environment. I think we should also add/improve the `Makefile`, but this can serve to help at least get some commands in the readme to help quickly setup the dev environment.
- Improve readme for development
=> [MLDEV-1123] Add some additional help to the readme for starting a simple dev environment

.gitignore, Makefile, README.md
This PR reworks some of the `Makefile` to make the development flow much smoother and quicker. We don't include the `airflow_provider_datarobot` as a package directly anymore and just point at a second `requirements_dev.txt` that is used after the initial image is built, but before the airflow environment is started. The `Makefile` will take care of adjusting the `Dockerfile` and `requirements_dev.txt` files during rebuilds.
The reason for using this slightly offset approach is that the `Docker` environment inside astro runs a few different commands, and the files are not present inside the container at the stage where the `requirements.txt` is read and executed. We need to wait until the initial container is constructed and execute a second `pip install` command between the initial …
=> [MLDEV-1126] Improve makefile commands for astro dev environments

CODEOWNERS
This is a rough first draft at attempting to allocate the review into the appropriate slack channels so it doesn't always ping the 3 people listed in the codeowners file. It could be good to improve this by adding in some linter automation for the codeowners file (e.g. `code-owners format -i` as supported in the monolith) and some checks related to this. First I just want to at least get it where the reviews are being spread out to the domains/individuals working on things.
I think that `machine-learning-development` is probably an ok owner of the base files, and `continuous-integration` can be tagged on harness related changes. Actual test/dag changes and other areas, we'll need to sort of identify as this project progresses and we can dynamically improve on the codeowners file.
- Make …
=> [MLDEV-1124] Update codeowners to have a more domain-oriented review process

CODEOWNERS
Add @datarobot/api-docs as the owner for the docs repo. Please let me know if this isn't the right team.
=> [MLDEV-1137] Add api docs as co-owner for docs in repo

datarobot_provider/hooks/credentials.py, datarobot_provider/operators/credentials.py, datarobot_provider/operators/datarobot.py, datarobot_provider/operators/feature_discovery.py, datarobot_provider/operators/monitoring.py, pyproject.toml
Tweak/alter the mypy config
By adding `enable_error_code = "ignore-without-code"` I believe this follows good practice to enforce contributors to ignore explicit errors if they are going to leverage the "ignore option"
I've then updated to add error codes to existing `ignore`'s
Also other updates to the mypy config I've found valuable.
I've added one config value commented out: `warn_return_any = true`
I believe it is a valuable addition however when running mypy _without_ it commented out we get:
`Found 23 errors in 13 files (checked 72 source files)`
=> [-] Tweaks to mypy config and ignore error code additions

Makefile, datarobot_provider/autogen/generate_operator.py, datarobot_provider/operators/gen/modeljob/__init__.py, datarobot_provider/operators/gen/modeljob/model_job_get_operator.py, pyproject.toml, requirements.txt, tests/fixtures/whitelist_test_output.txt, tests/unit/autogen/test_generate_operator.py
This:
1. Makes `generate_operator.py` into a script which can already be used to generate operators
2. Implements generation of imports
3. Adds POC generated operator to test the approach `datarobot_provider/operators/gen/modeljob/model_job_get_operator.py`
Problems:
Generated code gets minor fixes from `ruff`, I would prefer that we generate files which are always the same.
I have also added followups to https://datarobot.atlassian.net/browse/MLDEV-1169
=> [MLDEV-1170] Prepare script to generate stuff

CHANGES.md, datarobot_provider/operators/ai_catalog.py, tests/unit/operators/test_ai_catalog.py
Add a new operator: `CreateWranglingRecipeOperator`
Users should be able to create a recipe and use it in a recently added `CreateDatasetFromRecipeOperator`
=> [DM-16787] Add `CreateWranglingRecipeOperator` 

datarobot_provider/example_dags/deprecated/datarobot_custom_model_pipeline_dag.py, datarobot_provider/example_dags/deprecated/datarobot_replace_custom_model_pipeline_dag.py, pyproject.toml
Proposal to also use Ruff's Airflow rules - docs here:
https://docs.astral.sh/ruff/rules/#airflow-air
I think since we're using Ruff in this repo. and there were minimal errors it's a good opportunity to enable these checks
- Added Airflow ruff config so we check those rules
- Updated code to get rid of errors => `AIR001 Task variable name should match the `task_id``
=> [CFX-1398] Adding opt-in Airflow ruff checking

datarobot_provider/hooks/connections.py, datarobot_provider/hooks/credentials.py, datarobot_provider/operators/ai_catalog.py, datarobot_provider/operators/connections.py, pyproject.toml, tests/unit/hooks/credentials/test_aws_credentials.py, tests/unit/hooks/credentials/test_azure_credentials.py, tests/unit/hooks/credentials/test_basic_credentials.py, tests/unit/hooks/credentials/test_gcp_credentials.py, tests/unit/hooks/credentials/test_oauth_credentials.py
Added McCabe complexity rule (no issues):
https://docs.astral.sh/ruff/rules/#mccabe-c90
Then I found a handful of unused variables that ideally should be special `_` variable.
The way I discovered these was adding `preview = true` to the `[tool.ruff.lint]` section in pyproject.toml - I did _not_ commit that though but I can if we wish.
Putting lining rules in place while there's still very few violations to fix now.
=> [CFX-1398] Misc airflow repo updates related to ruff linting

datarobot_provider/example_dags/hospital_readmissions_example.py
This is a very simple dag, but it does run correctly and pretty fast on local or staging. All you need is to define a basic `datarobot_connection` and it runs.
Dag that does the following:
- Uploads a dataset (We can replace this with the wrangler pipeline)
- Creates a project
- Starts a Project
- Checks for autopilot completion
There are additional stages we need to add for the P0, but this gets us a running template to build from.
=> [MLDEV-1189] Add very basic hospital readmissions dag that we can build from

.harness/cichecks.yaml, CHANGES.md, datarobot_provider/operators/ai_catalog.py, datarobot_provider/operators/connections.py, pyproject.toml, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_connections.py
* Get a `data_store_id` based on the connection name.
* Make `CreateOrUpdateDataSourceOperator` more flexible:
* `dataset_name` parameter is now optional
* All parameters are templates now.
* Create a wrangling recipe from a db table. No intermediate dataset needed. 
* Datarobot relies on default credentials heavily in UXR. New API endpoints don't expect plain credentials anymore. So, users have to **prefer Datarobot over Airflow connections management**.
* We're going to build an example DAG with database wrangling. The PR prepares existing operators for this.
=> [DM-16784] Add a GetDataStoreOperator

datarobot_provider/operators/datarobot.py, docs/autodoc/operators_datarobot.md, tests/unit/operators/test_datarobot.py
This was one of the remaining MLDEV operators blocking the P0 DAG. This allows a pipeline to create a use case. It's a pretty simple operator. Also the docstring has been moved to numpy now so that it works with the docs properly.
- Add a new create use case operator
- Add a simple test
Followup:
We probably need to investigate if we should have a more robust operator/dag test strategy in place. It feels like the existing flow heavily just relies on mocking out the core pySDK call, and this doesn't necessarily check that the upstream call hasn't changed in any way.
=> [MLDEV-1174] Add use case create operator

CHANGES.md, datarobot_provider/operators/ai_catalog.py, tests/unit/operators/test_ai_catalog.py
We let users "publish" Feature Discovery datasets by creating new AI Catalog entries from their Feature Discovery project. So to allow users to publish, this PR updates to add `CreateDatasetFromProjectOperator`.
=> [DM-1903] Add CreateDatasetFromProjectOperator

.harness/cichecks.yaml, Makefile, pyproject.toml
This PR adds doc testing to the main `ci_checks` pipeline. It also unifies up some of the wording, and removes the manual `pip` commands and dependency on the `requirements.txt`. Instead everything now defers to the `make` commands which makes it more simple to update the pipelines.
Docs test is currently passing on this build.
I also split apart the `dev` and `docs` requirements so that these aren't needed in the regression matrix unit testing. This allows us to always use the latest docs versions for everything. A followup to this will formally remove the `requirements.txt` file now that the pipelines should not depend on it anymore.
=> [MLDEV-1144] Add docs testing to main ci checks pipeline

datarobot_provider/operators/ai_catalog.py, datarobot_provider/operators/autopilot.py, datarobot_provider/operators/base_datarobot_operator.py, datarobot_provider/operators/bias_and_fairness.py, datarobot_provider/operators/connections.py, datarobot_provider/operators/credentials.py, datarobot_provider/operators/custom_models.py, datarobot_provider/operators/datarobot.py, datarobot_provider/operators/deployment.py, datarobot_provider/operators/feature_discovery.py, tests/unit/operators/test_custom_models.py
Introduce a base class for all Datarobot operators. Apply it to operators modules from `a...` to `f...`. More updates to do in a subsequent PR.
There is quite a lot of repeatable codebase in the repo. Move it into the base class.
=> [DM-16986] Introduce a `BaseDatarobotOperator`

.harness/build_and_publish_early_access_pypi.yaml, .harness/input_sets/test_release_early_access_pypi.yaml, .harness/templates/publish_early_access_to_pypi_or_testpypi.yaml, setup.py, setup_early_access.py
This adds a new early access release pipeline with test as the default option here. Once this works ok, I'll create a separate mirror with `pypi` as the `BUILD_TYPE` which should formally release early access to pypi.
See the test build on test.pypi for the result of the pipeline running in test mode
https://test.pypi.org/project/airflow-provider-datarobot-early-access/
=> [MLDEV-1207] New early access test release pipeline

.harness/build_and_publish_early_access_pypi.yaml, .harness/release_early_access_pypi.yaml, .harness/templates/lint.yaml
This is a clone of the `test` variant of the pipeline, but where the release attribute is set to `pypi`. This will release an early access build.
See https://github.com/datarobot/airflow-provider-datarobot/pull/140 for the test pipeline PR. I will hold off on actually executing this pipeline for now.
- Add new release pipeline
- Convert `Lint repo` step to a template so that it can be re-used across all the release pipelines
- Update the test pypi early access pipeline to use the template
=> [MLDEV-1211] Add full Early Access release pipeline and update template for linter

Makefile
Pip versions higher than 24.1 can't handle DataRobot package versions, e.g.:
```
WARNING: Ignoring version 2.2.3.post1+dr of pandas since it has invalid metadata:
Requested pandas>=0.15 from https://artifactory.devinfra.drdev.io/artifactory/api/pypi/python-all/pandas/pandas-2.2.3.post1%2Bdr-cp312-cp312-linux_x86_64.whl#sha256=fe795d91c90ad9fa658e5c74a8e3ae9bacd6a91d925b8efb6babdea232704dce (from datarobot>=3.6.1->airflow_provider_datarobot==0.0.13) has invalid metadata: Local version label can only be used with `==` or `!=` operators
numpy>=1.26.4.post2+dr,<1.27
~~~~~~~~~~~~~~^
Please use pip<24.1 if you need to use this version.
```
Set an upper limit on the pip version install via `make req` so that we avoid this issue.
=> [DM-17020] Set upper limit on pip version (<24.1)

datarobot_provider/example_dags/hospital_readmissions_example.py, datarobot_provider/operators/ai_catalog.py, datarobot_provider/operators/base_datarobot_operator.py, datarobot_provider/operators/datarobot.py, datarobot_provider/operators/feature_discovery.py, tests/unit/conftest.py, tests/unit/operators/test_ai_catalog.py, tests/unit/operators/test_base_datarobot_operator.py, tests/unit/operators/test_datarobot.py
* Introduce a notion of a **default Use Case** for a DAG.
* Add a `BaseUseCaseEntityOperator` class
* Rename `CreateUseCaseOperator` into `GetOrCreateUseCaseOperator`
There are quite many DataRobot assets which have to belong to a UseCase. Define a default one in the very beginning of your DAG to avoid repetitive `use_case_id` parameters.
=> [DM-17022] Default use case

CHANGES.md, README.md, datarobot_provider/operators/model_registry.py, tests/unit/operators/test_model_registry.py
This operator is created to cover functionality of creating a registered model version for several different model types
- Leaderboard Model
- Custom Model 
- External Model
for detailed description you can follow update in readme file and for more details on [client side ](https://datarobot-public-api-client.readthedocs-hosted.com/en/latest-release/reference/mlops/model_registry.html#create-registered-model-version)
=> [mmm-18320] operator create registered model registered model version

datarobot_provider/operators/feature_discovery.py, tests/unit/operators/test_feature_discovery.py
In the normal Feature Discovery workflow we require version ID to be explicitly defined by the user.
We can simplify the user workflow for Airflow if we automatically get the version ID associated with a dataset when it isn't defined explicitly by the user.
=> [DM-17021] Get catalogVersionId if not defined by users

setup.py, setup_early_access.py
Update packaging that's used in build process
We need and want to exclude `_experimental` from _non_ early-access builds
- Removed usage of unsupported `python_versions` - checked [docs. here](https://setuptools.pypa.io/en/latest/references/keywords.html) after seeing warning in build output about param
- Updated to use `find_packages()` - [docs here](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#finding-simple-packages)
Here's resulting directory output of command `make build-release` (and then the extracted version of the `.tar.gz`):
<hr>
Here's resulting directory output of command `make build-early-access` (and then the extracted version of the `.tar.gz`):
=> [MLDEV-1175] Update packaging to only include `_experimental` when building early-access version of package

datarobot_provider/operators/feature_discovery.py, setup.py, tests/unit/operators/test_feature_discovery.py
We've just release another minor patch to the python client which enables several fixes to workarounds that were originally used for the Feature Discoery workflow.
This PR bumps the client to 3.6.2 and applies the relevant Feature Discovery changes.
=> [DM-16975] [DM-17066] Bump DataRobot client to 3.6.2 and apply relevant changes to Feature Discovery workflow

datarobot_provider/example_dags/hospital_readmissions_example.py
This param has to be defined as a metric for the project (e.g. RMSE, MSE, etc...). This fixes the dag so it runs in the test environments now.
We do need to probably add some better testing around this concept to ensure the example DAGs are fully working, but this is a bit of a challenging task and we're trying to sort this out as part of `MLDEV-1223` (currently in progress).
=> [MLDEV-1224] Fix input param in example dataset

.harness/release_pypi.yaml, CHANGES.md, datarobot_provider/__init__.py, datarobot_provider/_version.py
- Update the release pipeline to enable `pypi release`.
- Bump the tag version to 0.1.0 for this initial alpha release (plan is currently that the 11.0 final release will be v1.0.0).
- Make current changelog indicate 0.1.0 instead of unreleased.
=> [MLDEV-1225] Update and tag version 0.1.0 for release to pypi with P0 example DAG

setup.py, setup_early_access.py
Trying to pip install our package in a 3.13 virtual env fails:
`Collecting google-re2>=1.0 (from apache-airflow>=2.6.0->airflow-provider-datarobot)`
Looks like there's a known issue here:
https://github.com/google/re2/issues/516?email_source=slack
And also apache-airflow only declares support up to 3.12:
https://pypi.org/project/apache-airflow/
=> [CFX-1605] DR AF Provider - Remove declared python 3.13 support

setup.py
Add two new URLs
We should direct users to a specific place in order to report/search for/track bugs and issues
Also added a (somewhat redundant) source code URL
Currently our entry looks like this:
https://pypi.org/project/airflow-provider-datarobot/
<hr>
We'd like (IMHO) it to look more like apache-airflow's:
https://pypi.org/project/apache-airflow/
=> [CFX-1606] Add more project URLs that show in pypi - importantly the bug tracker

CHANGES.md, datarobot_provider/example_dags/deprecated_dags/__init__.py, datarobot_provider/example_dags/hospital_readmissions_xgboost_example.py, setup.py
This adds most of the stages for the xgboost example dag.  Currently we don't really have any way of testing dags outside of running them in a local or QA environment. This dag still needs an additional operator added for completion of everything. I'll update that in a followup.
On the side, I'm also exploring how possible it is to come up with some alternative form of testing if the dag loads properly without any errors. This would be something good to have, but I'm unsure how to do this on harness outside an active docker environment.
=> [MLDEV-1228] Add xgboost version of hospitlal readmissions example dag

datarobot_provider/autogen/generate_operator.py, datarobot_provider/constants.py, datarobot_provider/hooks/datarobot.py, datarobot_provider/operators/base_datarobot_operator.py, datarobot_provider/operators/gen/modeljob/model_job_get_operator.py, datarobot_provider/sensors/client.py, datarobot_provider/sensors/datarobot.py, datarobot_provider/sensors/model_insights.py, datarobot_provider/sensors/monitoring_job.py, tests/fixtures/whitelist_test_output.txt, tests/unit/autogen/test_generate_operator.py
Use constants instead of "[magic strings](https://en.wikipedia.org/wiki/Magic_string)"
I had recently added `DATAROBOT_CONN_ID` in my code addition for DR Notebooks support
I think this aids in code quality/readability/maintainability
=> [CFX-1510] Use constants where appropriate

.readthedocs.yaml
This PR adds in a config template for RTD to control generation of documentation for this repo.
Since this is a public repo, we can't add the docs to docs.datarobot.com just yet, so we need to get it ready for public documentation via another source: Read the Docs.
=> [-] Add Read the Docs Config in Preparation for RTD Generation

datarobot_provider/operators/datarobot.py
The `use_feature_discovery` parameter isn't an input option, but is instead used as an indicator of whether Feature Discovery was run **after** a project completes. Updated to remove the use of this parameter as an input via the context - this step has no effect and might mislead customers.
=> [DM-17115] Remove use of `use_feature_discovery` as input

.harness/build_and_publish_early_access_pypi.yaml, .harness/release_early_access_pypi.yaml, .harness/release_pypi.yaml, .harness/templates/publish_early_access_to_pypi_or_testpypi.yaml
Thanks to the help of IT, we now have access to both repositories. This updates the pipelines to inject the new stored secrets which are unique for each of the two repos.
Actual secrets are retrieved from the secure environments, so this is just updating the naming of how these are retrieved and changing the logic to indicate there are 2 different sets of secrets.
=> [MLDEV-1239] Update release pipelines for pypi and early-access pypi to have valid tokens

CODEOWNERS, docs/examples/hospital_readmissions_example.md, docs/examples/index.md, docs/index.md, docs/reference/index.md
This adds a small examples dropdown that we can easily expand, and an initial description + steps + needed feature flags for the first released example dag.
See screenshot below for html build:
=> [MLDEV-1235] Add documentation for first example dag

datarobot_provider/example_dags/hospital_readmissions_deployment_prediction_generation.py, datarobot_provider/operators/deployment.py, datarobot_provider/operators/monitoring.py, tests/unit/operators/test_deployment.py, tests/unit/operators/test_monitoring.py
added 1st step for model deployment from model registry and its operator
added 2nd step for setting data drift settings
=> [MMM-18684] p0 dag 2 deployment from registered model version implementation of first deployment step

datarobot_provider/example_dags/hospital_readmissions_deployment_prediction_generation.py, datarobot_provider/example_dags/hospital_readmissions_xgboost_example.py, datarobot_provider/example_dags/wrangler_example_recipe.py
This PR does the following:
- Upload a predictions dataset
- Apply a wrangler recipe (refactored this so its not duplicated as much in the examples)
- Score the wrangler dataset with the existing deployment id
=> [MLDEV-1243] Add deployment predictions dataset upload and scoring to example DAG

CHANGES.md, datarobot_provider/__init__.py, datarobot_provider/_version.py, datarobot_provider/operators/model_insights.py, docs/autodoc/operators_insights.md, tests/unit/operators/test_model_insights_job.py
This cleans up many of the insight operators.
Updates changelog and versions to 0.2.0.
- Add `ShapImpact` compute operator (simple operator with tests)
- Cleanup docstrings for the feature impact operators since they are using the correct calls to the API
- Add to docs
=> [MODEL-17045][MODEL-17046][MODEL-17053] Cleanup feature impact/effects docstrings and shap impact operator

.harness/cichecks.yaml, .harness/release_early_access_pypi.yaml, .harness/release_pypi.yaml, .harness/templates/unit_tests.yaml
This PR makes some cleanups to the release pipelines to make them quicker and more robust.
- Extract unit tests as a template
- Make `ci_checks` use the template
- Add `unit tests` to `early-access` and `mainline` release pipelines in parallel with lint
- Add `test-early-access-pypi` as a step before `early-access-pypi` so its just a single pipeline that needs to be run
=> [MODEL-18049] Update Early Access and Release pipelines to be more streamlined

.harness/release_early_access_trigger.yaml
This adds a yaml of the early access CRON trigger. This is set to release at 9:00AM EST, or 15:00 UTC.
**NOTE: Triggers are not synced with github, but its good to keep a copy of these in code format in the repo.**
=> [MODEL-18051] Add early access harness cron trigger to repo

tests/unit/operators/test_custom_models.py, tests/unit/operators/test_deployment.py, tests/unit/operators/test_model_retraining.py, tests/unit/operators/test_model_training.py
Fixes some calls to work on mac dev environments. The `validate` operation is actually called in the context of `pre_execute` which is called by airflow, but is not actually called if the user simply calls `operator.execute()` in the context of testing. This hooks leads to some tests not working correctly in some environments. These calls should be checking the `validate` function instead.
=> [MODEL-18068] Fix some tests that don't work right on latest mac dev env

datarobot_provider/operators/model_insights.py, docs/autodoc_operators/operators_insights.md, tests/unit/operators/test_model_insights_job.py
PR adds support for retrieving the roc curve information as a dictionary that can be used by other operators, along with the associated tests.
=> [MODEL-17041] Add get roc curve operator

CODEOWNERS
Update the codeowners based on the new org structure
=> [MODEL-18215] Update codeowners to point to predictive-ai instead of MLDEV

datarobot_provider/operators/datarobot.py, docs/autodoc_operators/operators_project_use_case.md, tests/unit/operators/test_datarobot.py
This PR adds a small operator to retrieve a list of the ids and types for all trained models in a project. I thought including the type alongside the ID as a tuple would be more convenient, because it could help users if they wanted to implement some additional processing.
PR includes tests and documentation updates.
=> [MODEL-17050] Operator to return a list of ids and type for all trained models in project

datarobot_provider/operators/model_training.py, docs/autodoc_operators/operators_model_training.md, tests/unit/operators/test_model_training.py
Add a simple operator to retrieve the basic dictionary of parameters for a `project_id` and `model_id`. This can be used for advanced tuning, to retrain a model with similar parameters, or just to log these parameters.
PR adds class, tests and documentation.
=> [MODEL-17042] Add get model parameters operator and tests

datarobot_provider/operators/segmentation.py, docs/autodoc_operators/operators_segmentation.md, tests/unit/operators/test_segmentation.py
This adds a wrapper to the `SegmentationTask.create()` functionality to create and retrieve a segmentation task id. This ID can then be paired with the pre-existing autopilot operators to start a segmented modeling project.
PR includes:
- New class
- Docs
- Tests for the new class
=> [MODEL-17059] Add segmentation task create operator, tests and docs

datarobot_provider/operators/queue.py, docs/autodoc_operators/operators_queue.md, tests/unit/operators/test_queue.py
This PR adds an operator which cancels a job is the `project_id` and `job_id` are provided. If the job has already completed, errored, or aborted, it will simply log that the job cannot be cancelled.
Tests and documentation added also.
=> [MODEL-17053] Add CancelJobOperator

datarobot_provider/operators/queue.py, docs/autodoc_operators/operators_queue.md, tests/unit/operators/test_queue.py
Add a new operator to retrieve the jobs of the specified status by their ids. The user determines the status when it is sent to the operator.
This PR also adds:
- Tests
- Docs
=> [MODEL-17056] Add operator to get jobs from queue

CHANGES.md, datarobot_provider/operators/model_training.py, docs/autodoc_operators/operators_model_training.md, tests/unit/operators/test_model_training.py
This PR adds a pair of cross validation operators (one for AutoML cross validation and the other for AutoTS backtests). This allows the user to trigger these jobs from the orchestration flows.
- Add `CrossValidateModelOperator`
- Add datetime version that inherits `CrossValidateModelOperator` as `ScoreBacktestsModelOperator`
- Add unit tests
- Add documentation
=> [MODEL-17047] Add cross validation operators

CHANGES.md, datarobot_provider/operators/model_insights.py, docs/autodoc_operators/operators_insights.md, tests/unit/operators/test_model_insights_job.py
Because each project can have many associated featurelists, it is important to know which features a model requires in order to run. This helps ensure that the necessary features are provided when generating predictions. This PR adds an operator to connect to this pySDK logic.
- Add `GetFeaturesUsedOperator` class
- Add unit tests for the class
- Update docs and changelog
=> [MODEL-17048] Retrieve the features used to train a model

.harness/release_early_access_pypi.yaml
Execute a custom release script using environment variables and service accounts to publish the mainline release formally to github before doing an official mainline release.
- Add `Release to Github` step
- Add environment variables to mainline release pipeline
- <s>[ ] Changelog entry updated (`CHANGES.md`).</s>
- <s>[ ] Documentation added or updated (if relevant).</s>
- <s>[ ] Tests added or updated (if relevant).</s>
=> [MODEL-18335] Add GitHub release creation to mainline release pipeline

.harness/createreleasepr.yaml, .harness/createreleasetag.yaml, .harness/release_pypi.yaml, .harness/templates/validate_commit_sha_1.yaml, .harness/templates/validate_release_version_tag_1.yaml, CHANGES.md
Final pipeline update PR. This adds two small templates that validate the `COMMIT_SHA` and `RELEASE_TAG_VERSION` inputs are correctly formatted in all of the pipelines that use them. This prevents accidental incorrect formatted values from attempting to run the pipelines. Incorrect values could succeed in some instances, and would cause problematic formatting issues if they did.
- Add `validate_release_version_tag` template
- Add `validate_commit_sha` template
- Update the 3 main release pipelines to check for values when needed using the templates
=> [MODEL-18396] Add safety checks to release pipelines

CHANGES.md, datarobot_provider/__init__.py, datarobot_provider/_version.py, datarobot_provider/example_dags/feature_discovery_retraining_and_scoring.py, datarobot_provider/operators/base_datarobot_operator.py, datarobot_provider/operators/data_registry.py, setup.py, tests/unit/operators/test_data_registry.py
- Don't allow `apache-airflow>=3.0` until the package is compatible.
- Update `feature_discovery_retraining_and_scoring` example DAG to work with a dynamic dataset.
- Update `CreateDatasetFromDataStoreOperator` to add a new dataset into use case.
=> [DM-17544] Support dynamic secondary dataset in feature discovery DAG

setup_early_access.py
Follow up to: https://github.com/datarobot/airflow-provider-datarobot/pull/234
Ensure we have the same ceiling set for early-access version.
- early-access version auto-release on Tuesdays
- early-access version is what is currently being used by the MLPipelines feature in MTS
Don't allow apache-airflow>=3.0 until the package is compatible.
=> [-] Set ceiling for apache-airflow to avoid breaking changes

datarobot_provider/_experimental/operators/notebook.py
We're changing the name of the `run()` method to be more verbose in the experimental client (before we move Notebooks APIs to GA)
PR here:
https://github.com/datarobot/public_api_client/pull/3658
- Account for rename of method
=> [CFX-2798] Account for renaming of method in experimental DR Python Client

CHANGES.md, Makefile, datarobot_provider/_experimental/operators/notebook.py, datarobot_provider/_experimental/sensors/notebook.py, datarobot_provider/operators/data_prep.py
Notebooks APIs are getting promoted to GA and as they do the next release of the python client (non early-access) will include these classes in a new location.
- Update imports to check new, GA location first
- Update Makefile to make nicer to work with
- Make update to data-prep file to get newest (`1.16.0`) mypy happy
With latest mypy of `1.16.0` there was an error ([seen here](https://app.harness.io/ng/account/oP3BKzKwSDe_4hCFYw_UWA/module/ci/orgs/AGENTS/projects/airflowproviderdatarobot/pipelines/cichecks/executions/N4jmJqfzSHCWVSbLEbznIg/pipeline?stage=TpTaAcVvTIiExFh5Eu0h3Q)):
<hr>
Now `make help` renders this:
=> [CFX-2801] Update NBX imports in anticipation of GA availability

CHANGES.md, docs/autodoc_operators/operators_notebook.md, docs/autodoc_sensors/sensors_notebook.md
Notebooks classes were not added to the docs when recently promoted to GA
This handles that.
<hr>
=> [CFX-3228] Notebooks classes were not added to the docs when recently promoted to GA
